version: "3.1"
services:

    redis:
      image: redis

    mysql:
      image: mysql:5.7
      container_name: db
      volumes:
        - .:/application:cached
      environment:
        - MYSQL_ROOT_PASSWORD=changeme
        - MYSQL_DATABASE=projectName
        - MYSQL_USER=changeme
        - MYSQL_PASSWORD=changeme
      ports:
        - "8082:3306"

    web:
      image: nginx:latest
      volumes:
          - .:/application:cached
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php:
      build: docker/php
      volumes:
        - .:/application:cached
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      links:
        - redis
